Auto commit - CI build

diff --git a/amazon-eks-ami/templates/shared/runtime/bin/cache-pause-container b/amazon-eks-ami/templates/shared/runtime/bin/cache-pause-container
--- a/amazon-eks-ami/templates/shared/runtime/bin/cache-pause-container
+++ b/amazon-eks-ami/templates/shared/runtime/bin/cache-pause-container
@@ -23,6 +23,14 @@ done
 PULL_ARGS=""
 if [[ "${PAUSE_CONTAINER_IMAGE}" == *"dkr.ecr"* ]]; then
   PULL_ARGS="${PULL_ARGS} --user AWS:$(aws ecr get-login-password)"
+elif [[ "${PAUSE_CONTAINER_IMAGE}" == *"public.ecr.aws"* ]]; then
+  # ECR public authentication must always be through us-east-1
+  # https://docs.aws.amazon.com/AmazonECR/latest/public/public-registry-auth.html
+  if ECR_PUBLIC_PASSWORD=$(aws ecr-public get-login-password --region=us-east-1); then
+    PULL_ARGS="${PULL_ARGS} --user AWS:${ECR_PUBLIC_PASSWORD}"
+  else
+    echo "Failed to authenticate to public ECR, retrying with unauthenticated pull" >&2
+  fi
 fi
 sudo ctr --namespace k8s.io image pull ${PULL_ARGS} ${PAUSE_CONTAINER_IMAGE}
 sudo ctr --namespace k8s.io image tag ${PAUSE_CONTAINER_IMAGE} ${TAG}
